// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDnSt62K0zIXJLZ74wBuDGT_VS8WE-FNdo',
  //   appId: '1:46329965836:web:2056368e07d06f1d53ed29',
  //   messagingSenderId: '46329965836',
  //   projectId: 'subtrack-a020a',
  //   authDomain: 'subtrack-a020a.firebaseapp.com',
  //   storageBucket: 'subtrack-a020a.firebasestorage.app',
  //   measurementId: 'G-67Q7V2H6GW',
  // );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDnSt62K0zIXJLZ74wBuDGT_VS8WE-FNdo",
    authDomain: "subtrack-a020a.firebaseapp.com",
    databaseURL: "https://subtrack-a020a-default-rtdb.firebaseio.com",
    projectId: "subtrack-a020a",
    storageBucket: "subtrack-a020a.firebasestorage.app",
    messagingSenderId: "46329965836",
    appId: "1:46329965836:web:2056368e07d06f1d53ed29",
    measurementId: "G-67Q7V2H6GW",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdZJSk9kDjuTwpXfnLGs3vuggGuikZa68',
    appId: '1:46329965836:android:fe30ce62d61adb3553ed29',
    messagingSenderId: '46329965836',
    projectId: 'subtrack-a020a',
    storageBucket: 'subtrack-a020a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmdSNxV5J2E61mi3IuEL1tyzecMSbPOyY',
    appId: '1:46329965836:ios:8e159bb6819b953d53ed29',
    messagingSenderId: '46329965836',
    projectId: 'subtrack-a020a',
    storageBucket: 'subtrack-a020a.firebasestorage.app',
    iosBundleId: 'com.example.substrack',
  );
}
